### ISSUE TITLE
KeyError: 'resp_type'

### ISSUE THREAD

**Issue by remonsec** [allyomalley/LiveTargetsFinder#4]
### Facing this error 

Traceback (most recent call last):
  File "liveTargetsFinder.py", line 309, in <module>
    main(targetHosts, massdnsPath, masscanPath, resolvers, useNmap, dbOutputPath)
  File "liveTargetsFinder.py", line 223, in main
    domain_map = processMassDNS(targetHosts, massdnsOutput, massdnsPath, resolvers, domainOutput, ipOutput)
  File "liveTargetsFinder.py", line 96, in processMassDNS
    domain_map = parseMassDNS(massdnsOutput)
  File "liveTargetsFinder.py", line 18, in parseMassDNS
    if (response['resp_type'] == 'A'):
KeyError: 'resp_type'

![issue](https://user-images.githubusercontent.com/54717234/80857534-c6586c00-8c74-11ea-93fa-d984c436cb5e.png)

**Comment by s0meguy1** [comment]
@mehedi1194 - see my most recent comment [here](https://github.com/allyomalley/LiveTargetsFinder/issues/3)
