### ISSUE TITLE
can you add a flag to add custom location of resolvers of massdns?

### ISSUE THREAD

**Issue by marcelo321** [allyomalley/LiveTargetsFinder#8]
It would be awesome to have that flag since I put custom location of massDNS but I get error on resolvers and there is no flag to select it.

**Comment by marcelo321** [comment]
Also getting this error :(

```
 - Massdns complete, parsing results...
Traceback (most recent call last):
  File "liveTargetsFinder.py", line 309, in <module>
    main(targetHosts, massdnsPath, masscanPath, resolvers, useNmap, dbOutputPath)
  File "liveTargetsFinder.py", line 223, in main
    domain_map = processMassDNS(targetHosts, massdnsOutput, massdnsPath, resolvers, domainOutput, ipOutput)
  File "liveTargetsFinder.py", line 96, in processMassDNS
    domain_map = parseMassDNS(massdnsOutput)
  File "liveTargetsFinder.py", line 18, in parseMassDNS
    if (response['resp_type'] == 'A'):
KeyError: 'resp_type'
```

**Comment by okpalindrome** [comment]
Download `https://github.com/blechschmidt/massdns/blob/master/lists/resolvers.txt` and place it under `/usr/lists/`
